format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[username]
# format = '[ $user](bold #99ffe4)@'
format = ' [$user](bold bright-yellow)@'
show_always = true

[hostname]
# format = '[$hostname](#ffc799)'
format = '[$hostname](bold bright-white)'
ssh_only = false

[directory]
# format = ' in [$path](bold #b9aeda) '
format = ' in $path '

[character]
success_symbol = "[ ●](bold purple)"
error_symbol = "[ ●](red)"
vimcmd_symbol = "[ ●](green)"

[git_branch]
format = "[$branch](bold #ff8080)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
